version: '3.8'

services:
  mongo:
    image: mongo
    container_name: operationDB
    ports:
      - "27019:27019"
    volumes:
      - mongo_data:/data/db

  microservice:
    build: .
    container_name: microservice-operation
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27019/operationDB

volumes:
  mongo_data: